name: build and deploy to vercel quaterly cron
on:
  push:
    branches:
      - master
  # 45分ずつに実行
  schedule:
    - cron: '*/45 * * * *'
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.ref }}

      #  vercelでのビルドが成功しないためactionsでビルドする
      - uses: actions/setup-node@v2
        with:
          node-version: '18'
      - name: Install Dependencies
        run: yarn install

      - name: Build Project
        shell: bash
        run: |
          yarn
          NOTION_KEY=${{ secrets.NOTION_KEY }}
          NOTION_DATABASE_ID=${{ secrets.NOTION_DATABASE_ID }}
          NEXT_PUBLIC_EMAILJS_PUBLIC_KEY=${{ secrets.NEXT_PUBLIC_EMAILJS_PUBLIC_KEY }}
          NEXT_PUBLIC_EMAILJS_TEMPLATE_ID=${{ secrets.NEXT_PUBLIC_EMAILJS_TEMPLATE_ID }}
          NEXT_PUBLIC_EMAILJS_SERVICE_ID=${{ secrets.NEXT_PUBLIC_EMAILJS_SERVICE_ID }} yarn build

      - uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.ORG_ID}}
          vercel-project-id: ${{ secrets.PROJECT_ID}}
          working-directory: ./
