name: deploy website
on:
  # for debug
  workflow_dispatch:
  push:
    branches:
      - master
  # 1時間ごとに実行
  schedule:
    - cron: '0 * * * *'
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.ref }}

      # ノードのバージョンを指定 18
      - uses: actions/setup-node@v2
        with:
          node-version: '18'
      - name: Install Dependencies
        run: yarn install

      - name: Build Project
        run: yarn build

      - uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.ORG_ID}}
          vercel-project-id: ${{ secrets.PROJECT_ID}}
          working-directory: ./
